version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns:
          - "astro"
          - "@astrojs/*"
          - "react"
          - "react-dom"
          - "tailwindcss"
          - "@tailwindcss/*"
